CREATE OR REPLACE TRIGGER bIC5_TB
BEFORE DELETE OR UPDATE OF trainee ON Sailors
FOR EACH ROW
DECLARE
	PRAGMA AUTONOMOUS_TRANSACTION; -- You’ll need this directive
BEGIN
	FOR E IN (SELECT S.TRAINEE, COUNT(*)
		FROM SAILORS S, BOATS B
		WHERE B.LOGKEEPER = :OLD.SID
		GROUP BY S.TRAINEE
		HAVING COUNT(*) > 0)
	LOOP
		RAISE_APPLICATION_ERROR (-20001,'+++++ DELETE or UPDATE rejected. Trainee ..'||:OLD.SID||'.. is a LogKeeper');
	END LOOP E;
END;
/
SHOW ERROR
